version: "2"
services:

  web:
    build:
      context: .
      dockerfile: container-build/web/Dockerfile
    environment:
    - MYSQL_DATABASE=AKC_project
    - MYSQL_USER=root
    - MYSQL_PASSWORD=Lola-29102019
    - MYSQL_HOST=AKC_project
    ports:
    - "8080:80"
    volumes:
    - .:/var/www
    depends_on:
    - db

  db:
    image: mysql:5.7
    ports:
    - "6603:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=Lola-29102019
    - MYSQL_USER=root
    - MYSQL_PASSWORD=Lola-29102019
    - MYSQL_DATABASE=AKC_project
    volumes:
    - "mysql_data:/var/lib/mysql"
    - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data: { driver: local }
